### ISSUE TITLE
Issue Parsing

### ISSUE THREAD

**Issue by GrantBirki** [ncalteen/issueops-terraform-example#1]
# Issue Parsing

👋 Hey there (fellow hubber)!

I stumbled across this repo and it looks pretty darn awesome. I wanted to put an Action on your radar that might help you out here!

I see you are doing some [issue parsing](https://github.com/ncalteen/issueops-terraform-example/blob/main/src/validate-issue.js). I actually worked on creating an Action that does exactly that and you may be able to just use it instead -> https://github.com/grantbirki/issue-template-parser

**Comment by GrantBirki** [comment]
PS I starred this repo (⭐) so I can follow along because this project looks rad!

**Comment by ncalteen** [comment]
Thanks for the feedback! I have this on my list to take a look at your issue template parser :) In testing so far, parsing and validation looks like it can be a bit of a sticking point for creating comprehensive IssueOps flows. This could definitely help!
